# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Generate Ensure API package and push it to NuGet Gallery.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore src/IOKode.OpinionatedFramework.Ensuring/IOKode.OpinionatedFramework.Ensuring.csproj

    - name: Build
      run: dotnet build src/IOKode.OpinionatedFramework.Ensuring/IOKode.OpinionatedFramework.Ensuring.csproj --no-restore

    - name: Test
      run: dotnet test src/IOKode.OpinionatedFramework.Ensuring/IOKode.OpinionatedFramework.Ensuring.csproj --no-build --verbosity normal

    - name: Pack
      run: dotnet pack src/IOKode.OpinionatedFramework.Ensuring/IOKode.OpinionatedFramework.Ensuring.csproj --no-build --configuration Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs

    - name: Push
      run: dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.Ensuring.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
