# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Generate OpinionatedFramework packages and push it to NuGet Gallery.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: |
        dotnet restore src

    - name: Build
      run: |
        dotnet build src/Foundation -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/ConfigureApplication -c Release /p:Version=${{ github.event.inputs.version }} --no-restore

        dotnet build src/ContractImplementations.Aes256GcmModeEncrypter -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/ContractImplementations.Bcrypt -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/ContractImplementations.CommandExecutor -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/ContractImplementations.FileSystem -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/ContractImplementations.GoogleCloudStorage -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/ContractImplementations.LocalFileSystem -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/ContractImplementations.MailKit -c Release /p:Version=${{ github.event.inputs.version }} --no-restore

        dotnet build src/Tests.Aes256GcmModeEncrypter -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/Tests.CommandExecutor -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/Tests.LocalFileSystem -c Release /p:Version=${{ github.event.inputs.version }} --no-restore
        dotnet build src/Tests.MailKit -c Release /p:Version=${{ github.event.inputs.version }} --no-restore

    - name: Test
      run: |
        dotnet test src/Tests.Aes256GcmModeEncrypter -c Release --no-build --verbosity normal
        dotnet test src/Tests.CommandExecutor -c Release --no-build --verbosity normal
        dotnet test src/Tests.LocalFileSystem -c Release --no-build --verbosity normal
        dotnet test src/Tests.MailKit -c Release --no-build --verbosity normal

    - name: Pack
      run: |
        dotnet pack src/Foundation --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/ConfigureApplication --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        
        dotnet pack src/ContractImplementations.Aes256GcmModeEncrypter --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/ContractImplementations.Bcrypt --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/ContractImplementations.CommandExecutor --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/ContractImplementations.FileSystem --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/ContractImplementations.GoogleCloudStorage --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/ContractImplementations.LocalFileSystem --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs
        dotnet pack src/ContractImplementations.MailKit --no-build -c Release /p:Version=${{ github.event.inputs.version }} --output ./nupkgs

    - name: Push
      run: |
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.Foundation.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ConfigureApplication.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ContractImplementations.Aes256GcmModeEncrypter.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ContractImplementations.Bcrypt.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ContractImplementations.CommandExecutor.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ContractImplementations.FileSystem.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ContractImplementations.GoogleCloudStorage.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ContractImplementations.LocalFileSystem.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./nupkgs/IOKode.OpinionatedFramework.ContractImplementations.MailKit.${{ github.event.inputs.version }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
